import { Button, VerticalBox } from "std-widgets.slint";
import "./NotoSans-Regular.ttf";


component row inherits Text {
    Rectangle {
        width: 140%;
        height: 50px;
        border-width: 3px;
        border-radius: 5px;
        border-color: #FFBB70;

        HorizontalLayout {
            padding-left: 15px;
            padding-right: 15px;
            alignment: space-between;
        
            Text {
                y: 11px;
                text: "MMMM - YYYY";
                font-size: 18px;
            }
            Rectangle {
                y: 10px;
                width: 3px;
                height: 30px;
                background: #FFBB70;
            }
            Text {
                y: 11px;
                text: "xxxx dkk";
                font-size: 18px;
                color: green;
            }
        }
    }
}

// component back-button inherits Rectangle {
//     y: 10px;
//     x: 10px;
//     width: 100px;
//     height: 40px;
//     background: #fff2d7;

//     Button {
//         text: "< Back";
//         padding: 0px;
//         preferred-width: 100%;
//         preferred-height: 100%;
//     }
// }

export component AppWindow inherits Window {
    in-out property <string> month: "February";
    in-out property <int> day: 11;

    callback request-update-date();

    background: #fff2d7;
    min-width: 400px;
    min-height: 500px;
    default-font-family: "Noto Sans";

    HorizontalLayout {
        alignment: center;
        Text { 
            text: "Budget App"; 
            y: 80px;
            font-size: 50px;
        }
    }
    HorizontalLayout {
        alignment: center;
        Rectangle {
            y: 170px;
            width: 130px;
            height: 40px;
            background: #D8AE7E;
            // border-width: px;
            border-radius: 5px;
            border-color: #F8C794;

            Button {
                text: "Upload CSV file";
                padding: 0px;
                preferred-width: 100%;
                preferred-height: 100%;
                clicked => { 
                    self.text = "Clicked"; 
                    root.request-update-date();
                    self.text = "Yo";
                }
            }
        }
    }
    HorizontalLayout {
        alignment: center;
        Text {
            text: "Last updated: \{root.day} of \{root.month}";
            y: 210px;
            font-size: 10px;
        }
    }
    my_budget_button := Rectangle {
        y: 10px;
        x: parent.width - 110px;
        width: 100px;
        height: 40px;
        background: #D8AE7E;
        border-radius: 5px;

        Button {
            text: "My budget";
            padding: 0px;
            preferred-width: 100%;
            preferred-height: 100%;
        }
    }
    // back_button := back-button {

    // }


    row {
        y: 250px;
    }
}
